### ISSUE TITLE
Add vesting with an optional cliff

### ISSUE THREAD

**Issue by deckardkrug** [radicle-dev/radicle-drips-hub#85]
Some DAOs vest their contributor payments over a certain timeframe or use what is called a cliff, which essentially allows a contributor to claim more of their vested tokens over time.

Scenario: Contributor requests 15k Float a month. The DAO does not know the contributor but if the contributor ships what was promised, they would be willing to pay that compensation.
They use the drips hub to establish a stream with a cliff which in the first months gives access to 6k, then in the second month he gets access to 7k and so on. The remaining compensation (i.e. 15k - 6k for the first month, gets payed after the 15k were reached in about 9 months).

**Comment by CodeSandwich** [comment]
This is an interesting use case! There could be 2 approaches:
1. The DAO promises (probably in form of a smart contract) that in X days they'll give the cliffed tokens and start dripping the vested ones. After X days they either set money in motion or cancel the agreement. This use case is already supported by drips hub.
2. The DAO sets up drips so that in X days the cliffed tokens will be dripped over the duration of 1 second and after that the vested tokens are dripped in a regular pace. The DAO can cancel the agreement at any time, but if it doesn't do anything, it's automatically executed. This is a use case for [scheduled drips](https://github.com/radicle-dev/radicle-drips-hub/issues/84).

**Comment by CodeSandwich** [comment]
I think that we've covered this use case with scheduled drips
